// app/routes/account-statement.tsx


export default function AccountStatement() {
  return (
    <div className="min-h-screen bg-gray-100 p-10">
      <div className="max-w-5xl mx-auto bg-white p-8 rounded shadow-md">
        <header className="text-center mb-8">
          <h1 className="text-3xl font-bold text-blue-700">Salaama Bank</h1>
          <p className="text-gray-600">We understand your security</p>
        </header>
        <div className="mb-8 border p-4">
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <p><strong>Account Number:</strong> 203354782654001</p>
              <p><strong>A/C Open Date:</strong> 12/04/2015</p>
              <p><strong>Account Branch:</strong> Eastleigh </p>
              <p><strong>IFSC Code:</strong> 56021A115</p>
            </div>
            <div>
              <p><strong>Address:</strong> 21A, Colombo street, 4th cross, MG Road, Eastleigh </p>
              <p><strong>City:</strong> Eastleigh 560076</p>
              <p><strong>State:</strong> Nairobi </p>
              <p><strong>Email:</strong> divyatlng0@gmail.com</p>
              <p><strong>Phone No:</strong>0701 989 8582</p>
              <p><strong>Account Type:</strong> Saving</p>
            </div>
          </div>
          <p><strong>Account Statement For The Period 1/01/2022 to 2/02/2022</strong></p>
        </div>
        <table className="w-full border-collapse">
          <thead>
            <tr className="bg-gray-200">
              <th className="border p-2 text-left">Date</th>
              <th className="border p-2 text-left">Narration</th>
              <th className="border p-2 text-right">Withdrawal Amount</th>
              <th className="border p-2 text-right">Deposit Amount</th>
              <th className="border p-2 text-right">Total Balance</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border p-2">4/01/22</td>
              <td className="border p-2">CASH DEP BAGALUR CROS</td>
              <td className="border p-2 text-right">1,110.00</td>
              <td className="border p-2 text-right">-</td>
              <td className="border p-2 text-right">9,882.30</td>
            </tr>
            <tr>
              <td className="border p-2">26/01/22</td>
              <td className="border p-2">IGST-LOCKER CHARGES-NCB2032 385463563</td>
              <td className="border p-2 text-right">-</td>
              <td className="border p-2 text-right">30,000.00</td>
              <td className="border p-2 text-right">38,472.50</td>
            </tr>
            <tr>
              <td className="border p-2">1/02/22</td>
              <td className="border p-2">POS 652166XXXXXX8647 IT WORLD</td>
              <td className="border p-2 text-right">30,999.00</td>
              <td className="border p-2 text-right">-</td>
              <td className="border p-2 text-right">9,473.50</td>
            </tr>
          </tbody>
        </table>
        <footer className="mt-8">
          <p>Generated On: 29-Nov-2020 15:31</p>
          <p>Generated By: Requesting Branch</p>
          <p>Code: NET</p>
          <p className="mt-4"><strong>Salaama Microfinance BANK</strong></p>
          <p className="text-sm text-gray-600">Contents of this statement will be considered correct if no error is reported within 30 days of receipt of statement. The address on this statement is that on record with the Bank as at the day of requesting this statement.</p>
          <p className="text-sm text-gray-600">State account branch GSTN: 29AAACH5702L1ZWY</p>
        </footer>
      </div>
    </div>
  );
}
